### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'sync')

### ISSUE THREAD

**Issue by MarcosRava** [flamewow/nestjs-asyncapi#219]
**Describe the bug**
When a try to run jest test in a class that has `@AsyncApiService` or `@AsyncApiPub` decorator I receive this error when I create an instance of the class

**To Reproduce**
My class
```ts

@Injectable()
@AsyncApiService()
export class KycPublisher implements IKycPublisher {

  @AsyncApiPub({
    channel: 'KYC_CREATE_TOPIC',
    summary: 'Send test packet',
    description: 'method is used for test purposes',
    message: {
      name: 'test data',
      payload: {
        type: MemberGetMemberDto,
      },
    },
  })
  async publish(topic: NotificationTopic, event: KycEvent): Promise<void> {
      // ...
  }
}

export const KycPublisherProvider = {
  provide: IKycPublisher,
  useClass: KycPublisher,
};
```
Test file
```ts
import { KycPublisher } from './kyc.publisher';

describe('KycPublisher', () => {
  let publisher: KycPublisher;

  beforeEach(() => {
    publisher = new KycPublisher();
  });
  it('should do nothing', async () => {

  });
});

```

Teste output
```sh
● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'sync')

      at Object.<anonymous> (../node_modules/@babel/core/lib/gensync-utils/resolve.js:31:27)
      at Object.<anonymous> (../node_modules/@babel/core/lib/config/files/configuration.js:65:39)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        14.069 s
```
My ts config
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "resolveJsonModule": true,
    "paths": {
      "src": ["src"]
    },
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}

```
My jest setup
```ts
import 'reflect-metadata';
```

My jest package setup
```json

  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "moduleDirectories": [
      "./",
      "node_modules"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s",
      "!<rootDir>/module/main.(t|j)s",
      "!**/*index.(t|j)s",
      "!**/*.port.(t|j)s",
      "!**/*.dto.(t|j)s",
      "!**/*.setup.(t|j)s",
      "!**/port/*.(t|j)s"
    ],
    "coverageThreshold": {
      "global": {
        "lines": 80,
        "statements": 80,
        "functions": 80
      }
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node",
    "setupFilesAfterEnv": [
      "../jest.setup.ts"
    ]
  }
```

**Expected behavior**
Should not throw error on tests using async decorators 

Nest version: 8.0.0

Check whether this is still an issue in the most recent Nest version
 
For Tooling issues:
- Node version: 16  
- Platform: Mac

**Comment by MarcosRava** [comment]
My async api setup

```ts
import { INestApplication } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {
  AsyncServerObject,
  AsyncApiDocumentBuilder,
  AsyncApiModule,
} from 'nestjs-asyncapi';
import { PublisherConfig } from 'src/config/publisher.config';
import { version } from '../../../../package.json';

export const setupAsyncApi = async (app: INestApplication) => {
  const docRelPath = '/async-api';
  const configService = app.get(ConfigService);
  const publisherConfig = configService.get<PublisherConfig>('publisher');
  const asyncApiServer: AsyncServerObject = {
    url: publisherConfig.pubEndPoint,
    protocol: publisherConfig.pubProtocol,
    description: 'Send Kyc events to SNS',
    bindings: {},
  };

  const asyncApiOptions = new AsyncApiDocumentBuilder()
    .setTitle('Kyc Events')
    .setDescription('Kyc events')
    .setVersion(version)
    .setDefaultContentType('application/json')
    .addServer('cats-server', asyncApiServer)
    .build();

  const asyncApiDocument = await AsyncApiModule.createDocument(
    app,
    asyncApiOptions,
  );
  await AsyncApiModule.setup(docRelPath, app, asyncApiDocument);
};

```

**Comment by flamewow** [comment]
@MarcosRava hey, would be nice to have minimal reproduction repo.

**Comment by MarcosRava** [comment]
@flamewow Ok, I'll try to make one

**Comment by pavlikm** [comment]
@MarcosRava  There is no problem with asyncapi decorators and tests. I use asyncapi decorators in 12 services, fully covered with unit tests with jest, and have no problemm. 
In your error message you can see, that this error is caused because some configuration of your app cant be reached. I suppose, that this import is your issue: 
`import { PublisherConfig } from 'src/config/publisher.config';`
Try to rewrite it to relative path

**Comment by flamewow** [comment]
closed due to inactivity
