### ISSUE TITLE
Any string as payload type causes error

### ISSUE THREAD

**Issue by Sergei8888** [flamewow/nestjs-asyncapi#282]
```
message: {
            name: 'Error message',
            payload: {
                type: 'string'
            }
        },
```
Error: Token "" does not exist.
    at dereference (/home/sergei888/GitLab/uniscope/src/backend_nest/node_modules/@asyncapi/parser/lib/parser.js:160:11)
    at parse (/home/sergei888/GitLab/uniscope/src/backend_nest/node_modules/@asyncapi/parser/lib/parser.js:95:5)
    at Generator.generateFromString (/home/sergei888/GitLab/uniscope/src/backend_nest/node_modules/@asyncapi/generator/lib/generator.js:265:22)

**Comment by flamewow** [comment]
Would you like to create a PR for this?

**Comment by flamewow** [comment]
message: {
      name: 'test data',
      payload: {
        type: String,
      },
    },
