### ISSUE TITLE
There were errors validating the AsyncAPI document addBearerAuth

### ISSUE THREAD

**Issue by rom4ukbro** [flamewow/nestjs-asyncapi#461]
An example of how I include the asyncAPI documentation in my nestjs project.
```
const asyncApiOptions = new AsyncApiDocumentBuilder()
    .setTitle('Socket docs')
    .setVersion(process.env.npm_package_version)
    .addBearerAuth(
      {
        description: 'Please enter firebase JWT token',
        name: 'Authorization',
        bearerFormat: 'Bearer',
        scheme: 'Bearer',
        type: 'http',
        in: 'Header',
      },
      'user-token',
    )
    .build();

const asyncApiDocument = await AsyncApiModule.createDocument(
    app,
    asyncApiOptions,
  );
  await AsyncApiModule.setup('docs/socket', app, asyncApiDocument);
```

Without addBearerAuth everything works fine, but when I add it I get an error
```
[Nest] 9932  - 16.02.2023, 16:11:53   ERROR [AsyncApiModule] Error: There were errors validating the AsyncAPI document.

D:\Project\PHEONIX\node_modules\@asyncapi\parser\lib\parser.js:113
    if (!valid) throw new ParserError({
                      ^
Error: There were errors validating the AsyncAPI document.
    at parse (D:\Project\PHEONIX\node_modules\@asyncapi\parser\lib\parser.js:113:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Generator.generateFromString (D:\Project\PHEONIX\node_modules\@asyncapi\generator\lib\generator.js:265:22)

```

the only settings it works with for me
```
    .addBearerAuth(
      {
        description: 'Please enter firebase JWT token',
        bearerFormat: 'Bearer',
        type: 'http',
      },
      'user-token',
    )
```

Sorry for my English, I'm from Ukraine. By the way, thanks for your support

**Comment by flamewow** [comment]
@rom4ukbro я з Украіни також 

Yeah, those are the only fields that are applicable to 'http' type, according to the https://www.asyncapi.com/docs/reference/specification/v2.5.0#securitySchemeObject

thanks for spotting an opportunity for improvement "adding specific types per security type". Btw, feel free to open PR if you have the capacity to work on the improvement 🙌
