### ISSUE TITLE
This template is not compatible with the current version of the generator

### ISSUE THREAD

**Issue by Alfagun74** [flamewow/nestjs-asyncapi#515]
**Describe the bug**

Upon generation on node:20.8 image

```
error:   ┏ This template is not compatible with the current version of the generator (1.10.9). This template is compatible with the following version range: >=1.13.0 <2.0.0. +46s
error:   ┃ [ 1] Error: This template is not compatible with the current version of the generator (1.10.9). This template is compatible with the following version range: >=1.13.0 <2.0.0.
error:   ┃ [ 2]     at isTemplateCompatible (/app/node_modules/.pnpm/@asyncapi+generator@1.10.9_@types+node@20.8.7/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:47:11)
error:   ┃ [ 3]     at module.exports.validateTemplateConfig (/app/node_modules/.pnpm/@asyncapi+generator@1.10.9_@types+node@20.8.7/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:25:3)
error:   ┃ [ 4]     at Generator.generate (/app/node_modules/.pnpm/@asyncapi+generator@1.10.9_@types+node@20.8.7/node_modules/@asyncapi/generator/lib/generator.js:179:5)
error:   ┃ [ 5] {
error:   ┃ [ 6]   context: 'AsyncApiModule',
error:   ┃ [ 7]   error: Error: This template is not compatible with the current version of the generator (1.10.9). This template is compatible with the following version range: >=1.13.0 <2.0.0.
error:   ┃ [ 8]       at isTemplateCompatible (/app/node_modules/.pnpm/@asyncapi+generator@1.10.9_@types+node@20.8.7/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:47:11)
error:   ┃ [ 9]       at module.exports.validateTemplateConfig (/app/node_modules/.pnpm/@asyncapi+generator@1.10.9_@types+node@20.8.7/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:25:3)
error:   ┃ [10]       at Generator.generate (/app/node_modules/.pnpm/@asyncapi+generator@1.10.9_@types+node@20.8.7/node_modules/@asyncapi/generator/lib/generator.js:179:5),
error:   ┃ [11]   timestamp: '2023-10-23T12:40:51.819Z'
error:   ┗ [12] }
```

**Environment**

Nest version: 10.2.7

Check whether this is still an issue in the most recent Nest version
 
For Tooling issues:
- Node version: 20.8.1
- Platform:  Linux

Others:
- Works on my Debian WSL with same Node version

**Comment by flamewow** [comment]
what nestjs-asyncapi version is that?

**Comment by hocaron** [comment]
@flamewow 

Hello, flamewow. I also have a similar issue, so I have a question.
I'm using `nestjs-asyncapi@1.3.0`, and I'm using pnpm as my package manager.
Here is my pnpm-lock.yml file.

```
  /nestjs-asyncapi@1.3.0(@nestjs/common@10.3.3)(@nestjs/core@10.3.3)(@nestjs/swagger@7.3.0)(@nestjs/websockets@10.3.3)(@swc/core@1.3.107)(@types/node@18.16.20):
    resolution: {integrity: sha512-ZtCrPdGGPBIRupI+Zt/9EmYuO6gU9O7snLB81on1nLIoir0pPcWCzIjiq5FafVwiHrV4ideUWklWdqh/xZU5PQ==}
    peerDependencies:
      '@nestjs/common': ^10.0.0 || ^9.0.0
      '@nestjs/core': ^10.0.0 || ^9.0.0
      '@nestjs/swagger': ^7.0.0 || ^6.0.0
      '@nestjs/websockets': ^10.0.0 || ^9.0.0
    peerDependenciesMeta:
      '@nestjs/websockets':
        optional: true
    dependencies:
      '@asyncapi/generator': 1.13.1(@swc/core@1.3.107)(@types/node@18.16.20)
      '@asyncapi/html-template': 0.28.4
      '@nestjs/common': 10.3.3(reflect-metadata@0.1.14)(rxjs@7.8.1)
      '@nestjs/core': 10.3.3(@nestjs/common@10.3.3)(@nestjs/platform-express@10.3.3)(@nestjs/websockets@10.3.3)(reflect-metadata@0.1.14)(rxjs@7.8.1)
      '@nestjs/swagger': 7.3.0(@nestjs/common@10.3.3)(@nestjs/core@10.3.3)(reflect-metadata@0.1.14)
      '@nestjs/websockets': 10.3.3(@nestjs/common@10.3.3)(@nestjs/core@10.3.3)(@nestjs/platform-socket.io@10.3.3)(reflect-metadata@0.1.14)(rxjs@7.8.1)
      js-yaml: 4.1.0
      reflect-metadata: 0.2.1
    transitivePeerDependencies:
      - '@swc/core'
      - '@swc/wasm'
      - '@types/babel__core'
      - '@types/node'
      - bluebird
      - bufferutil
      - canvas
      - encoding
      - supports-color
      - utf-8-validate
    dev: false
  ```
  
  This is error message.
  
```javascript
Error: This template is not compatible with the current version of the generator (1.13.1). This template is compatible with the following version range: >=1.15.0 <2.0.0.
    at isTemplateCompatible (/Users/hocaron/IdeaProjects/heylu-backend/node_modules/.pnpm/@asyncapi+generator@1.13.1_@swc+core@1.3.107_@types+node@18.16.20/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:56:11)
    at module.exports.validateTemplateConfig (/Users/hocaron/IdeaProjects/heylu-backend/node_modules/.pnpm/@asyncapi+generator@1.13.1_@swc+core@1.3.107_@types+node@18.16.20/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:29:3)
    at Generator.generate (/Users/hocaron/IdeaProjects/heylu-backend/node_modules/.pnpm/@asyncapi+generator@1.13.1_@swc+core@1.3.107_@types+node@18.16.20/node_modules/@asyncapi/generator/lib/generator.js:188:5)
```
